name = "sbgamers-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CACHE"
id = "c6a237d1753346a38c6400fb6e8b7dc9"

[[d1_databases]]
binding = "DB"
database_name = "sbgamers-db"
database_id = "6ee666e5-aea6-4e9f-bcf5-0a95c04fe6ec"

[triggers]
crons = ["0 2 * * *"]

[vars]
ENVIRONMENT = "production"
